x-spiri-sdk-doc: |
  Runs the core services for a simulated Spiri Mu    

x-spiri-sdk-autostart: True

services:
  ardupilot:
    network_mode: host
    image: ghcr.io/spiri-robotics/ardupilot:spiri-master
    command:
      - /bin/bash
      - -c
      - |
        ./Tools/autotest/sim_vehicle.py -v copter -f gazebo-mu --model=JSON --no-rebuild \
        -I$MAVLINK_SYS_ID --no-mavproxy --sim-address=$SIM_ADDRESS --sysid $MAVLINK_SYS_ID --out=tcp:127.0.0.1:5770
    stdin_open: true
    ports:
      - "5760:5760/udp"
      - "5770:5770/tcp"
    expose:
      - "5770"
    tty: true
    restart: always

  mavproxy:
    image: ghcr.io/spiri-robotics/services-mavproxy:main
    network_mode: host
    command: >
      mavproxy.py --non-interactive
      --master tcp:127.0.0.1:$ARDUPILOT_PORT
      --out udpout:127.0.0.1:14552
      --out tcpin:0.0.0.0:5760      
    stdin_open: true
    tty: true      
    restart: always

  mavros2:
    image: ghcr.io/spiri-robotics/services-ros2-mavros:main
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: ros2 launch mavros apm.launch fcu_url:="udp://127.0.0.1:14552@:14555" namespace:="$ROBOT_NAME" tgt_system:="$MAVLINK_SYS_ID"
    network_mode: host
    expose:
      - '14552'
    restart: always
    depends_on:
      ardupilot:
        condition: service_started
      mavproxy:
        condition: service_started
    deploy:
      resources:
        limits:
          # cpus: '0.01'
          memory: 200M
    ulimits:
      nofile:
        soft: 1024
        hard: 524288