services:
  spiri-sdk:
    build: ./
    volumes:
      - ./:/app
      #Mount the docker socket to allow the container to communicate with the host Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8197:8197"