[project]
name = "sdk-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docker>=7.1.0",
    "loguru>=0.7.3",
    "nicegui>=2.16.1",
    "pytest>=8.3.5",
    "requests>=2.32.3",
]

